#!/bin/bash
find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;
chmod 777 stylesheets/application.css
chmod 777 stylesheets/jquery.scroller.css
chmod 755 fixchmod
chmod 755 compile_sass